/*
 * Robot service 3.0
 * API сервис управления роботом - пылесосм.
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Group;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GroupApi
 */
@Ignore
public class GroupApiTest {

    private final GroupApi api = new GroupApi();

    /**
     * Добавление группы
     *
     * Добавление группы в базу данных
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addGroupTest() throws Exception {
        Group body = null;
        Group response = api.addGroup(body);

        // TODO: test validations
    }
    /**
     * Удаление группы по ID
     *
     * Удаление группы в базе данных
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteGroupTest() throws Exception {
        Long groupId = null;
        String groupId = null;
        api.deleteGroup(groupId, groupId);

        // TODO: test validations
    }
    /**
     * Поиск группы по ID
     *
     * Поиск группы в базе данных
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGroupByIdTest() throws Exception {
        Long groupId = null;
        Group response = api.getGroupById(groupId);

        // TODO: test validations
    }
    /**
     * Обновление группы пользователей
     *
     * Обновить группу пользователей
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateGroupTest() throws Exception {
        Group body = null;
        Group response = api.updateGroup(body);

        // TODO: test validations
    }
}
