/*
 * Robot service 3.0
 * API сервис управления роботом - пылесосм.
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Добавить пользователя
     *
     * Добавить пользователя в базу
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addUserTest() throws Exception {
        User body = null;
        User response = api.addUser(body);

        // TODO: test validations
    }
    /**
     * Удаление пользователя
     *
     * Удаление пользователя и базы данных
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws Exception {
        Long userId = null;
        String userId = null;
        api.deleteUser(userId, userId);

        // TODO: test validations
    }
    /**
     * Поиск пользователя по ID
     *
     * Поиск пользователя в базе
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws Exception {
        Long userId = null;
        User response = api.getUserById(userId);

        // TODO: test validations
    }
    /**
     * Обновить пользвателя
     *
     * Обновить пользователя в базе
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws Exception {
        Long userId = null;
        User response = api.updateUser(userId);

        // TODO: test validations
    }
}
