# coding: utf-8

# flake8: noqa
"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.group import Group
from swagger_client.models.robot import Robot
from swagger_client.models.schedule import Schedule
from swagger_client.models.user import User
