# coding: utf-8

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class User(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'email': 'str',
        'pass_hash': 'int',
        'robot_sn_hash': 'int'
    }

    attribute_map = {
        'id': 'id',
        'email': 'email',
        'pass_hash': 'passHash',
        'robot_sn_hash': 'robotSNHash'
    }

    def __init__(self, id=None, email=None, pass_hash=None, robot_sn_hash=None):  # noqa: E501
        """User - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._email = None
        self._pass_hash = None
        self._robot_sn_hash = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.email = email
        self.pass_hash = pass_hash
        self.robot_sn_hash = robot_sn_hash

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501


        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.


        :param email: The email of this User.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def pass_hash(self):
        """Gets the pass_hash of this User.  # noqa: E501


        :return: The pass_hash of this User.  # noqa: E501
        :rtype: int
        """
        return self._pass_hash

    @pass_hash.setter
    def pass_hash(self, pass_hash):
        """Sets the pass_hash of this User.


        :param pass_hash: The pass_hash of this User.  # noqa: E501
        :type: int
        """
        if pass_hash is None:
            raise ValueError("Invalid value for `pass_hash`, must not be `None`")  # noqa: E501

        self._pass_hash = pass_hash

    @property
    def robot_sn_hash(self):
        """Gets the robot_sn_hash of this User.  # noqa: E501


        :return: The robot_sn_hash of this User.  # noqa: E501
        :rtype: int
        """
        return self._robot_sn_hash

    @robot_sn_hash.setter
    def robot_sn_hash(self, robot_sn_hash):
        """Sets the robot_sn_hash of this User.


        :param robot_sn_hash: The robot_sn_hash of this User.  # noqa: E501
        :type: int
        """
        if robot_sn_hash is None:
            raise ValueError("Invalid value for `robot_sn_hash`, must not be `None`")  # noqa: E501

        self._robot_sn_hash = robot_sn_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(User, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
