# coding: utf-8

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.group_api import GroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_group(self):
        """Test case for add_group

        Добавление группы  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Удаление группы по ID  # noqa: E501
        """
        pass

    def test_get_group_by_id(self):
        """Test case for get_group_by_id

        Поиск группы по ID  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Обновление группы пользователей  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
