# coding: utf-8

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.robot_api import RobotApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRobotApi(unittest.TestCase):
    """RobotApi unit test stubs"""

    def setUp(self):
        self.api = RobotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_robot(self):
        """Test case for add_robot

        Добавление робота-пылесоса  # noqa: E501
        """
        pass

    def test_delete_robot(self):
        """Test case for delete_robot

        Удаление робота-пылесоса по ID  # noqa: E501
        """
        pass

    def test_get_robot_by_id(self):
        """Test case for get_robot_by_id

        Поиск робота-пылесоса по ID  # noqa: E501
        """
        pass

    def test_update_robot(self):
        """Test case for update_robot

        Обновление робота-пылесоса  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
