# coding: utf-8

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.robot import Robot  # noqa: E501
from swagger_client.rest import ApiException


class TestRobot(unittest.TestCase):
    """Robot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRobot(self):
        """Test Robot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.robot.Robot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
