# coding: utf-8

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.schedule_api import ScheduleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self):
        self.api = ScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_schedule(self):
        """Test case for add_schedule

        Добавление расписания  # noqa: E501
        """
        pass

    def test_delete_schedule(self):
        """Test case for delete_schedule

        Удаление расписания по ID  # noqa: E501
        """
        pass

    def test_get_schedule_by_id(self):
        """Test case for get_schedule_by_id

        Поиск расписания по ID  # noqa: E501
        """
        pass

    def test_update_schedule(self):
        """Test case for update_schedule

        Обновление расписания уборки  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
