# coding: utf-8

# flake8: noqa

"""
    Robot service 3.0

    API сервис управления роботом - пылесосм.  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.group_api import GroupApi
from swagger_client.api.robot_api import RobotApi
from swagger_client.api.schedule_api import ScheduleApi
from swagger_client.api.user_api import UserApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.group import Group
from swagger_client.models.robot import Robot
from swagger_client.models.schedule import Schedule
from swagger_client.models.user import User
